#!/usr/bin/env bash
# Regenerate portfolio/PORTFOLIO.md from each product's STATUS.md and META.md.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
out="$ROOT/portfolio/PORTFOLIO.md"
field(){ sed -nE "s/^- \*\*$1:\*\* (.*)/\1/p" "$2" | head -1; }
{
  echo "# Portfolio"
  echo
  echo "Generated by scripts/status.sh on $(date +%F). Do not edit by hand."
  echo
  echo "| Product | Status | Stage | Next step | Blockers |"
  echo "|---|---|---|---|---|"
  for d in "$ROOT"/products/p[0-9][0-9][0-9]-*/; do
    [ -d "$d" ] || continue
    name=$(basename "$d")
    st=$(sed -nE 's/^\| status \| (.*) \|$/\1/p' "$d/META.md" 2>/dev/null | head -1)
    echo "| $name | ${st:-?} | $(field 'Current stage' "$d/STATUS.md") | $(field 'Next step' "$d/STATUS.md") | $(field 'Blockers' "$d/STATUS.md") |"
  done
} > "$out"
cat "$out"
